### ISSUE TITLE
help me, mario sunshine switch

### ISSUE THREAD

**Issue by heraldo1980** [LagoLunatic/GCFT#11]
please, look at the rom gcm that is coming now in the new mario sunshine of the switch of the all stars 3d version, it opened and does not open anymore, could you help?

**Comment by LagoLunatic** [comment]
What you're asking isn't clear at all. But it sounds like it has to do with the Switch version of the game, which I don't support. This project is only for *GameCube* games.

If whatever the issue is also affects the GameCube version of SMS, open a new issue explaining what the exact issue is.
