### ISSUE TITLE
Continuação... 

### ISSUE THREAD

**Issue by heraldo1980** [LagoLunatic/GCFT#12]
Sorry, my english is not very good, in the SMS game of the switch, before the final update, there was a game cube game inside, a normal GCM, I could open it normally like a normal game cube ROM, now in this new one game update the GCM came different and does not open anywhere, would you like me to send you the link of the new GCM for you to look?

**Comment by LagoLunatic** [comment]
Why does it not open? What is the error message? You can take a screenshot.

> would you like me to send you the link of the new GCM for you to look?

No, that would be piracy.
