### ISSUE TITLE
error

### ISSUE THREAD

**Issue by heraldo1980** [LagoLunatic/GCFT#13]
![image](https://user-images.githubusercontent.com/79229121/169627058-c359419f-62af-4538-a179-8156eb4b2a1e.png)

**Comment by heraldo1980** [comment]
if it's that gcm error in the new rom of mario sunshine do switch that I had told you, if you could fix your program just for this game I would be very grateful.

**Comment by LagoLunatic** [comment]
What is the path to the GCM? I extracted the files from Super Mario 3D All-Stars, but I see no GCMs anywhere.
![image](https://user-images.githubusercontent.com/19174152/169628859-267529eb-c366-47c5-9b41-bdc91cd5f954.png)

**Comment by heraldo1980** [comment]
why did you extract mario galaxy, mario sunshine is in another ID. I will show the way...

**Comment by LagoLunatic** [comment]
I didn't extract Super Mario Galaxy. I extracted Super Mario 3D All-Stars using Ryujinx.

**Comment by heraldo1980** [comment]
there are 3 ID, a mario galaxy, or mario sunshine and by and mario 64, the way to extract mario sunshine is different by another extractor, I will send my media fire account and there you get the already extracted gcm, so we will avoid piracy.

**Comment by LagoLunatic** [comment]
> I will send my media fire account and there you get the already extracted gcm, so we will avoid piracy.

That's not "avoiding piracy", it's still illegal.

Just tell me how to extract it myself and stop wasting my time. Otherwise I'm closing this and not going to consider helping you further.

**Comment by heraldo1980** [comment]
forget it friend I won't take your time anymore, you can close.
