### ISSUE TITLE
Where is the gamecube's game file format documented?

### ISSUE THREAD

**Issue by badasahog** [LagoLunatic/GCFT#16]
I know this isn't directly related to this project in particular, but I'm working on something that uses GameCube iso files, and was hoping to inquire about their format. 

If you would be willing to link me to the resource you used when developing this project I would greatly appreciate it.

**Comment by LagoLunatic** [comment]
Can't remember the exact details as it was over 5 years ago that I first coded my GCM implementation, but I think this is the main page I referenced: http://hitmen.c02.at/files/yagcd/yagcd/chap13.html#sec13

I also seem to recall that some of the more nitty-gritty practical details weren't documented anywhere I could find, so I dug into Dolphin's source code to learn how they read the format.

Neither of those explain how to write arbitrarily modified files back to a GCM, so I pretty much just figured that out myself.
