### ISSUE TITLE
enhanced and more generic support for GameCube banner .bnr file format

### ISSUE THREAD

**Issue by BorgNumberOne** [LagoLunatic/GCFT#8]
Hi,

with the help of CleanRip I could create a library of all my GameCube Games.

Now, I would like to create a printable .xls / .html list in this way (to keep the order / overview of the different game's categories) (language, subtitle, language of the spoken words inside the game, Stereo/Dolby support, multiplayer support/amount of players, etc...):

[game 1 banner  logo] | [game 1 file name] | [game 1 spoken language] | [game 1 subtitle language] | [game 1 multiplayer support]
[game 2 banner  logo] | [game 2 file name] | [game 2 spoken language] | [game 2 subtitle language] | [game 2 multiplayer support]
[game x banner  logo] | [game x file name] | [game x spoken language] | [game x subtitle language] | [game x multiplayer support]
...

So I did look around which GameCube .gcm / .iso  tool is able to extract the banner (.bnr) file of my GameCube disc image files:

**Dolphin Emulator**
 -->able to extract the banner, but without alpha transparency information --> many backgrounds in the converted opening_bnr.png files are black.

**GameCube ISO analyzer / editor 1.2 ("Version 1.1.0.32537")**
 --> no capability of extracting /converting the GameCube Banner file (.bnr)

**Nintendo GameCube images rebuilder (GCRebuilder) v1.1**
 --> able to extract/convert the opening.bnr banner to .bmp, but without alpha transparency information -->many backgrounds in the converted opening_bnr.png files are white.

**GC-Tool v 1.20 (beta)**
 --> able to extract/convert the opening.bnr banner to .bmp, but without alpha transparency information -->many backgrounds in the converted opening_bnr.png files are white.

**GC Explorer 1.06**
 --> able to display the GameCube banner of the currently opened GameCube disc image file - alpha transparency information is interpreted as white, but no possibility to convert the .bnr GameCube banner file.

**GameCube File Tools**
 --> able to extract the banner, including alpha transparency information --> this seems to be the only tool that has the feature.

Are there further tools?

Well, inside the **GameCube File tools** I cannot simply open any .bnr file (from a certain folder or drive) and convert it to .png.

Furthermore, I cannot simply convert a .bnr file from inside a .gcm file.

I have to open a GameCube .gcm / .iso file.
Then I have to select the "opening.bnr" file inside the opened GameCube .gcm / .iso file.
Then I have to use the right mouse button to open the contect menu on/at "opening.bnr".
Then I have to select "Open Image"
Then the "GameCube File Tools" automatically switches to the tab: "BTI Images" and displays the current GameCube banner logo.
Then I have to select Export Image.

It would be great, If I could directly select "Export image" in the opening.bnr's context menu (and in the context menu of .bnr files generally) directly in the file "GCM ISOs" file browser/file overview.

Furthermore, the "GameCube File Tools" offers the "Open Image" context menu entry just/only for "**opening.bnr**" files - a general .bnr file format support would be great.
There are many GameCube disc images which have additional .bnr(beside the opening.bnr) .bnr files inside, e.g.:

Finding Nemo (EUR): **opening1.bnr**
Beyond Good and Evil(EUR): **save.bnr**
Charlie and the Chocolate Factory: **eu_bnr.bnr**, **us_bnr.bnr**
Narnia (GameCube ID: GLVD4Q) German release: **opening.bnr.FR** **opening.bnr.UK**
Aging Test For Production. try59 (Disc 1, Revision 7) (GameCube ID 102E01) (google: "e99720d85cef42615adbbf1a6e943a41" or: "gamecube aging disc"): **bye-opening.bnr**

**Comment by LagoLunatic** [comment]
> It would be great, If I could directly select "Export image" in the opening.bnr's context menu (and in the context menu of .bnr files generally) directly in the file "GCM ISOs" file browser/file overview.

Why? It only saves one click (for something that rarely needs to be done), clogs up the context menu, and isn't consistent with how GCFT's UI works for every other type of file.

> Furthermore, the "GameCube File Tools" offers the "Open Image" context menu entry just/only for "**opening.bnr**" files - a general .bnr file format support would be great.
> There are many GameCube disc images which have additional .bnr(beside the opening.bnr) .bnr files inside, e.g.:

Odd, according to dolphin's source code it will only load the file names "opening.bnr" specifically, so I assume the same thing applies to actual GameCube hardware. I guess the extra ones you mentioned are unused ones the devs left in the files. Either way I guess it wouldn't hurt to support those.

**Comment by BorgNumberOne** [comment]
Many thanks for the insightful understanding and implementing the mentioned ideas.
Please, could you also publish a recent binary release with the new features?

How can I make a donation?

**Comment by LagoLunatic** [comment]
Released a new version now, I don't take donations for romhacking

**Comment by BorgNumberOne** [comment]
The previous GameCube banner logo file handler was: just accepting "opening.bnr".
In the last release of GCFT it looks like you did improve it to: "*.bnr".
But the best would be:
"**[asterisk placeholder]**.bnr.**[asterisk placeholder]**" OR
"**[asterisk placeholder]**.bnr **[asterisk placeholder]**" (without period after **bnr**)

for example in cases like this one:
Narnia (GameCube ID: GLVD4Q) German release: opening.bnr.FR opening.bnr.UK

Furthermore, it would be great if **direct .bnr file support** could be added: **BTI Images** tab --> **import BNR**

Thanks a lot for your great efforts.

**Comment by AlfredoDore** [comment]
I have a question, in Zelda Collection Edit Zelda I and II are in Opening.BNR, I want to replace the roms with the translated ones and even try adding other NES games, but I don't know which tool can edit
